#!/bin/bash
# Does the equivalent of sysprep for linux boxes to prepare them for cloning.
# Based on https://gist.github.com/AfroThundr3007730/ff5229c5b1f9a018091b14ceac95aa55

say() {
    printf '%s: %s\n' "$(date -u +%FT%TZ)" "$@"
}

config_vmware_tools() {
    say 'Install vmware-tools.'
    if [[ $FEDORA_DERIV == true ]]; then
        yum install -y open-vm-tools perl
        systemctl enable vmtoolsd.service
        systemctl start vmtoolsd.service
    elif [[ $DEBIAN_DERIV == true ]]; then
        apt install -y open-vm-tools perl
        systemctl enable open-vm-tools.service
        systemctl start open-vm-tools.service
    fi

    say 'Enable vmware-tools customization scripts.'
    vmware-toolbox-cmd config set deployPkg enable-custom-scripts true

    say 'Disable cloud-init.'
    [ -d "/etc/cloud" ] && \
        touch /etc/cloud/cloud-init.disabled

    return 0
}

clean_packages() {
    say 'Clearing package.'
    if [[ $FEDORA_DERIV == true ]]; then
        /usr/bin/yum clean all -q &> /dev/null
        /bin/rm -rf /var/cache/yum/*
    elif [[ $DEBIAN_DERIV == true ]]; then
        /usr/bin/apt clean &> /dev/null
        /bin/rm -rf /var/cache/apt/archives/*
    fi
    return 0
}

clean_logs() {
    say 'Clearing old logs.'
    /usr/sbin/logrotate -f /etc/logrotate.conf
    /usr/bin/find /var/log -type f -regextype posix-extended -regex \
        ".*/*(-[0-9]{8}|.[0-9]|.gz)$" -delete
    /bin/rm -rf /var/log/journal && /bin/mkdir /var/log/journal
    /bin/rm -f /var/log/dmesg.old
    /bin/rm -f /var/log/anaconda/*

    say 'Clearing audit logs.'
    [ -f "/var/log/audit/audit.log" ] && \
        : > /var/log/audit/audit.log
    : > /var/log/wtmp
    : > /var/log/lastlog
    : > /var/log/grubby
    
    return 0
}

FEDORA_IFCFG_ENS192=$(cat << EOF
DEVICE=ens192
ONBOOT=yes
EOF
)
clean_network() {
    say 'Clearing udev persistent rules.'
    if [ -f /etc/udev/rules.d/70-persistent-net.rules ]; then
        rm /etc/udev/rules.d/70-persistent-net.rules
    fi

    say 'Removing network config.'
    if [[ $FEDORA_DERIV == true ]]; then
        echo "$FEDORA_IFCFG_ENS192" > \
            /etc/sysconfig/network-scripts/ifcfg-ens192
    elif [[ $DEBIAN_DERIV == true ]]; then
        rm -f /etc/netplan/*
        rm -f /etc/NetworkManager/system-connections/*
    fi
    grep -q 'Generated by NetworkManager' /etc/resolv.conf && \
        : > /etc/resolv.conf

    return 0
}

clean_files() {
    say 'Cleaning out temp directories.'
    /bin/rm -rf /tmp/*
    /bin/rm -rf /var/tmp/*
    /bin/rm -rf /var/cache/*

    say 'Cleaning up root home directory.'
    unset HISTFILE
    /bin/rm -f /root/.bash_history
    /bin/rm -f /root/anaconda-ks.cfg
    /bin/rm -rf /root/.ssh/
    /bin/rm -rf /root/.gnupg/

    return 0
}

DEB_SSH_OVERRIDE_CONF=$(cat << EOF
# https://www.cyberciti.biz/faq/howto-regenerate-openssh-host-keys/
[Service]
ExecStartPre=
ExecStartPre=-/usr/bin/ssh-keygen -A
ExecStartPre=/usr/sbin/sshd -t
EOF
)
clean_ssh_keys() {
    say 'Removing SSH host keys.'
    rm -f /etc/ssh/ssh_host_*

    if [[ $DEBIAN_DERIV == true ]]; then
        mkdir -p /etc/systemd/system/ssh.service.d
        echo "$DEB_SSH_OVERRIDE_CONF" > \
            /etc/systemd/system/ssh.service.d/regenerate-ssh-host-keys.conf
    fi

    return 0
}

generalize() {
    say 'Clearing machine-id.'
    truncate -s 0 /etc/machine-id
    rm -f /var/lib/dbus/machine-id
    ln -s /etc/machine-id /var/lib/dbus/machine-id

    say 'Removing random-seed.'
    /bin/rm -f /var/lib/systemd/random-seed

    say 'Resetting hostname.'
    truncate -s 0 /etc/hostname
    [ "$(hostname)" != "localhost.localdomain" ] && \
        sed -i "/$(hostname)/d" /etc/hosts
    hostnamectl set-hostname localhost

    return 0
}

sysprep() {
    source /etc/os-release
    if [[ $ID      =~ (fedora|rhel|centos) || $ID_LIKE =~ (fedora|rhel|centos) ]]; then
        FEDORA_DERIV=true
    elif [[ $ID      =~ (debian|ubuntu|mint) || $ID_LIKE =~ (debian|ubuntu|mint) ]]; then
        DEBIAN_DERIV=true
    else
        say 'An unknown base linux distribution was detected.'
        say 'This script works with Debian and Fedora based distros.'
        exit 1
    fi

    say 'Stopping logging and auditing daemons.'
    /bin/systemctl stop rsyslog.service
    /usr/sbin/service auditd stop

    config_vmware_tools

    clean_packages

    clean_logs

    clean_network

    clean_files

    clean_ssh_keys

    generalize

    say 'End of sysprep.'

    exit 0
}

# Only execute if not being sourced
[[ ${BASH_SOURCE[0]} == "$0" ]] && sysprep "$@"
